apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clamav.fullname" . }}-client-config
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
data:
  clamd.conf: |
    ###############
    # General
    ###############

    DatabaseDirectory /data
    TemporaryDirectory /tmp
    LogTime yes
    PidFile /run/clamd.pid
    TCPSocket 3310
    TCPAddr {{ include "clamav.fullname" . }}-server.{{ .Release.Namespace }}.svc.cluster.local
    Foreground yes
    ExcludePath /host-fs/dev
    ExcludePath /host-fs/sys
    ExcludePath /host-fs/var/lib/docker

    ###############
    # Results
    ###############

    DetectPUA yes
    ExcludePUA NetTool
    ExcludePUA PWTool
    HeuristicAlerts yes
    Bytecode yes

    ###############
    # Scan
    ###############

    ScanPE yes
    DisableCertCheck yes
    ScanELF yes
    AlertBrokenExecutables no
    ScanOLE2 yes
    ScanPDF yes
    ScanSWF yes
    ScanMail yes
    PhishingSignatures yes
    PhishingScanURLs yes
    ScanHTML yes
    ScanArchive yes

    ###############
    # Scan
    ###############

    MaxScanSize 150M
    MaxFileSize 30M
    MaxRecursion 10
    MaxFiles 15000
    MaxEmbeddedPE 10M
    MaxHTMLNormalize 10M
    MaxHTMLNoTags 2M
    MaxScriptNormalize 5M
    MaxZipTypeRcg 1M
    MaxPartitions 128
    MaxIconsPE 200
    PCREMatchLimit 10000
    PCRERecMatchLimit 10000