{{- if .Values.client.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clamav.client.serviceAccountName" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
  {{- with .Values.client.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
