{{- if .Values.ingress.enabled -}}
{{- if gt (len .Values.ingress.hosts) 0 -}}
{{- $fullName := include "questdb.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "questdb.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ $fullName }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: {{ $fullName }}
            servicePort: 9000
        {{- if .Values.service.expose.healthcheck.enabled }}
        - path: /healthcheck
          pathType: Exact
          backend:
            serviceName: {{ $fullName }}
            servicePort: 9003
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
