{{- if .Values.privateIngress.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $allPrivateHosts := concat .Values.privateIngress.hosts  -}}
{{- $customPaths := .Values.privateIngress.custom_paths -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-private
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
spec:
  ingressClassName: {{ .Values.privateIngress.privateIngressClass }}
  rules:
  {{- range $allPrivateHosts }}
    - host: {{ . }}
      http:
        paths:
          {{ if gt (len $customPaths) 0 }}
          {{- range $customPaths }}
          - path: {{ .path }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}                
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
              {{- else }}
              serviceName: {{ .serviceName }} 
              servicePort: {{ .servicePort }}
              {{- end }}
          {{- end }}
          {{ else }}
          - {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
          {{ end }}
  {{- end }}
{{- end }}