{{- if .Values.ingress.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $customPaths := .Values.ingress.custom_paths -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta" -}}
apiVersion: networking.k8s.io/v1beta
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    {{- if gt (len $customPaths) 0 }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- end }}
    {{- if .Values.ingress.tls }}
    {{- if not (hasKey .Values.ingress.annotations "cert-manager.io/cluster-issuer")}}
    {{- if .Values.ingress.wildcard }}
    cert-manager.io/cluster-issuer: letsencrypt-prod-wildcard
    {{- else }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
    {{- end }}
    {{- end }}
    # provider-agnostic default annotations
    # if value is provided as "null" or null, it is unset 
    {{- if gt (len .Values.ingress.annotations) 0}}
    {{- range $k, $v := .Values.ingress.annotations }}
    {{- if $v}}
    {{- if and (not (eq $v "null")) $v}}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
        {{- range .Values.ingress.porter_hosts }}
        - {{ . }}
        {{- end }}
      {{ if .Values.ingress.wildcard }}
      secretName: wildcard-cert-tls
      {{ else }}
      secretName: {{ include "docker-template.fullname" . }}  
      {{ end }}
  {{- end }}

  rules:
    {{- range .Values.ingress.hosts }}
      - host: {{ . }}
        http:
          paths:
            {{ if gt (len $customPaths) 0 }}
            {{- range $customPaths }}
            - path: {{ .path }}
              pathType: Prefix
              backend:
                {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}                
                service:
                  name: {{ .serviceName }}
                  port:
                    number: {{ .servicePort }}
                {{- else }}
                serviceName: {{ .serviceName }} 
                servicePort: {{ .servicePort }}
                {{- end }}
            {{- end }}
            {{ else }}
            - backend:
              pathType: Prefix
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
              {{- else }}
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
              {{- end }}
            {{ end }}
    {{- end }}
    {{- range .Values.ingress.porter_hosts }}
      - host: {{ . }}
        http:
          paths:
            {{ if gt (len $customPaths) 0 }}
            {{- range $customPaths }}
            - path: {{ .path }}
              pathType: Prefix
              backend:
                {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}                
                service:
                  name: {{ .serviceName }}
                  port:
                    number: {{ .servicePort }}
                {{- else }}
                serviceName: {{ .serviceName }} 
                servicePort: {{ .servicePort }}
                {{- end }}
            {{- end }}
            {{ else }}
            - backend:
              pathType: Prefix
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
              {{- else }}
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
              {{- end }}
            {{ end }}
    {{- end }}
{{- end }}