{{- if .Values.ingress.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"

    # provider-agnostic default annotations
    {{ if gt (len .Values.ingress.annotations) 0}}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{ end }}

    {{ if gt (len .Values.ingress.custom_paths) 0 }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{ end }}


    {{ if .Values.ingress.wildcard }}
    cert-manager.io/cluster-issuer: letsencrypt-prod-wildcard
    {{ else }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{ end }}
spec:
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . }}
        {{- end }}
        {{- range .Values.ingress.porter_hosts }}
        - {{ . }}
        {{- end }}
      {{ if .Values.ingress.wildcard }}
      secretName: wildcard-cert-tls
      {{ else }}
      secretName: {{ include "docker-template.fullname" . }}  
      {{ end }}

  rules:
    {{- range .Values.ingress.hosts }}
      - host: {{ . }}
        http:
          paths:
            {{ if gt (len .Values.ingress.custom_paths) 0 }}
            {{- range $index, $custom_path := .Values.ingress.custom_paths }}
            - path: {{ $custom_path.path }}
              backend:
                serviceName: {{ $custom_path.serviceName }}
                servicePort: {{ $custom_path.servicePort }}
            {{- end }}
            {{ else }}
            - backend:
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
            {{ end }}
    {{- end }}
    {{- range .Values.ingress.porter_hosts }}
      - host: {{ . }}
        http:
          paths:
            {{ if gt (len .Values.ingress.custom_paths) 0 }}
            {{- range $index, $custom_path := .Values.ingress.custom_paths }}
            - path: {{ $custom_path.path }}
              backend:
                serviceName: {{ $custom_path.serviceName }}
                servicePort: {{ $custom_path.servicePort }}
            {{- end }}
            {{ else }}
            - backend:
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
            {{ end }}
    {{- end }}
{{- end }}