apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-template.fullname" . }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
spec:
  {{ if .Values.ingress.enabled }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and .Release.IsUpgrade (not .Values.ingress.enabled) }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "docker-template.selectorLabels" . | nindent 4 }}
