{{- if .Values.cloudsql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "cloudsql-secret-{{ include "docker-template.fullname" . }}"
type: Opaque
stringData:
  service_account.json: {{ .Values.cloudsql.serviceAccountJSON | quote }}  
{{- end }}
