{{- if ne .Values.image.repository "public.ecr.aws/o1j4x7p4/hello-porter-job" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "docker-template.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "docker-template.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "docker-template.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
