{{- if not .Values.schedule.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "docker-template.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "docker-template.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "docker-template.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
