{{- if ne .Values.image.repository "public.ecr.aws/o1j4x7p4/hello-porter-job" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-template.fullname" . }}
  labels:
    getporter.dev/manifest: "true"
data:
  manifest: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{ .Release.Name }}-{{ randAlphaNum 10 | lower }}"
      namespace: {{ .Release.Namespace | quote }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        helm.sh/revision: "{{ .Release.Revision }}"
        meta.helm.sh/release-name: "{{ .Release.Name }}"
    spec:
      backoffLimit: 0
      template:
        metadata:
          name: "{{ .Release.Name }}"
          labels:
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
            helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            helm.sh/revision: "{{ .Release.Revision }}"
            meta.helm.sh/release-name: "{{ .Release.Name }}"
        spec:
          restartPolicy: Never
          shareProcessNamespace: true
          tolerations:
          - key: "removable"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: "{{ .Values.image.pullPolicy }}"
            {{- if and .Values.container.command (not (or (eq .Values.image.repository "porterdev/hello-porter-job") (eq .Values.image.repository "public.ecr.aws/o1j4x7p4/hello-porter-job"))) }}
            command: 
            {{- range $command := trim .Values.container.command | split " " }}
            - {{ $command | quote }}
            {{- end }}
            {{- end }}
            env:
            {{- range $key, $val := .Values.container.env.normal }}
            - name: {{ $key }}
            {{- $splVal := split "_" $val -}}
            {{- if and (len $splVal | eq 2) (eq $splVal._0 "PORTERSECRET") }}
              valueFrom:
                secretKeyRef:
                  name: {{ $splVal._1 }}
                  key: {{ $key }}
            {{- else }}
              value: {{ quote $val }}
            {{- end }}
            {{- end }}
            resources:
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}
              limits:
                memory: {{ .Values.resources.requests.memory }}
          - name: sidecar
            image: public.ecr.aws/o1j4x7p4/job-sidecar:latest
            imagePullPolicy: Always
            securityContext:
              capabilities:
                add:
                - SYS_PTRACE
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 10Mi
            command:
            - "./job_killer.sh"
            {{- if (.Values.sidecar.signalChildProcesses) }}
            - "-c"
            {{- end }}
            - {{ .Values.terminationGracePeriodSeconds | quote }}
            {{- $cmdSpl := trim .Values.container.command | split " " }}
            - {{ $cmdSpl._0 | quote }}
            {{- if .Values.cloudsql.enabled }}
            - "cloud_sql_proxy"
            {{- end }}
          {{- if .Values.cloudsql.enabled }}
          - name: cloud-sql-proxy
            image: gcr.io/cloudsql-docker/gce-proxy:1.17
            command:
              - "/cloud_sql_proxy"
              - "-instances={{ .Values.cloudsql.connectionName }}=tcp:{{ .Values.cloudsql.dbPort }}"
              - "-credential_file=/secrets/service_account.json"
            securityContext:
              runAsNonRoot: true
            volumeMounts:
            - name: "sidecar-volume-{{ include "docker-template.fullname" . }}"
              mountPath: /secrets/
              readOnly: true
          {{ end }}
          {{ if .Values.cloudsql.enabled }}
          volumes:
            - name: "sidecar-volume-{{ include "docker-template.fullname" . }}"
              secret:
                secretName: "cloudsql-secret-{{ include "docker-template.fullname" . }}"
          {{ end }}
          
{{- end }}