{{- if .Values.wildcard.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  # insert your DO access token here
  access-token: "{{ .Values.wildcard.do_access_token }}"
{{- end }}
